### ISSUE TITLE
无法捕捉

### ISSUE THREAD

**Issue by nova286** [warmlight/UncaughtExceptionHandler#2]
这个项目只有在demo工程里有效，在我们的项目里并不能起到作用，请问有什么好的方案吗

**Comment by nova286** [comment]
[AppDelegate string]: unrecognized selector sent to instance 0x7fbfa351f540
libc++abi.dylib: terminate_handler unexpectedly threw an exception

上面是xcode控制台的输出

**Comment by warmlight** [comment]
不好意思才看到你的issue 请问是否在- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions方法中添加了[UncaughtExceptionHandler installUncaughtExceptionHandler:YES showAlert:YES];这个方法？没有起到作用是指连指定的错误log都没有输出吗？还是没有弹出警示框？在我们项目里 自己写捕获异常是辅助方法 主要是通过友盟来收集 如果可以的话 你们项目可以加入友盟的崩溃收集 也是免费的 不知道能不能帮到你

**Comment by nova286** [comment]
谢谢你的回答，这个问题后来我调试过了，是因为项目里加了友盟统计的SDK，所以我们自定义的方法没有起作用
